### ISSUE TITLE
Parameters sharing across LiftDownPool layers

### ISSUE THREAD

**Issue by ghost** [jiaozizhao/LiftPool#1]
Hello, thanks for an interesting work. While reading the paper, I had a question. Do you share learning parameters across different LiftDownPool layers?

**Comment by jiaozizhao** [comment]
Thanks for being interested in this work. I did not share the parameters across different LiftDownPool layers. But seems worth trying.

**Comment by ghost** [comment]
> Thanks for being interested in this work. I did not share the parameters across different LiftDownPool layers. But seems worth trying.

Okay, thank you for an answer.
