### ISSUE TITLE
Parameters sharing in LiftDownPool2d

### ISSUE THREAD

**Issue by ghost** [jiaozizhao/LiftPool#3]
Could you help me to understand if you are sharing LiftPool1d parameters inside the LiftPool2d layer? I'm a little bit confused of it.
Citation from your paper ('Parameter Efficiency' section):  "_A 2D LiftDownPool shares these parameters three times without extra
parameters_".
Citation from [this answer](https://openreview.net/forum?id=kE3vd639uRW&noteId=CoGeGn--oEi): "_A 2D LiftPool has 3(C * K + C) parameters_".

**Comment by jiaozizhao** [comment]
Sorry for the confusion.  The updated paper with 'A 2D LiftDownPool shares these parameters three times without extra
parameters' is correct. I am busy with another submission. I Will clean and share the code after that.

**Comment by IvanYevtushenko** [comment]
> Sorry for the confusion. The updated paper with 'A 2D LiftDownPool shares these parameters three times without extra
> parameters' is correct. I am busy with another submission. I Will clean and share the code after that.
Great, thanks!

**Comment by ghost** [comment]
Great, thanks!
